rt_cache improvement

diff --git a/home/.bashrc.d/rt_cache b/home/.bashrc.d/rt_cache
--- a/home/.bashrc.d/rt_cache
+++ b/home/.bashrc.d/rt_cache
@@ -9,6 +9,21 @@ function rt_cache () {
 
   [ -x "${RT_BIN}" ] || return 0 || exit 0
 
+  refresh_rt_cache () {
+    ${rt_command} |       \
+      grep -v '^Query:Status' \
+      grep -v '^Ticker.Owner.Queue' \
+      grep -v '^-------------------------' \
+      > "${RTCACHE_FILE_TMP}"
+    RET=$?
+    if [ $RET -eq 0 ];then
+      mv -f "${RTCACHE_FILE_TMP}" "${RTCACHE_FILE}"
+    else
+      echo -e 'RT command Failed' >&2
+    fi
+    rmdir "$RTCACHE_LOCKDIR"
+  }
+
   local FORCE_REFRESH=0
   case $1 in
     -r|--refresh)
@@ -38,16 +53,7 @@ function rt_cache () {
     if mkdir "$RTCACHE_LOCKDIR" 2>/dev/null ;then
       trap 'rmdir "$RTCACHE_LOCKDIR"; exit $?' INT TERM EXIT
       echo -e "WARNING: cache expired. Refreshing rt cache in background. Displaying 'old' tasks"
-      (
-      ${rt_command} > "${RTCACHE_FILE_TMP}"
-      RET=$?
-      if [ $RET -eq 0 ];then
-        mv -f "${RTCACHE_FILE_TMP}" "${RTCACHE_FILE}"
-      else
-        echo -e 'RT command Failed      '
-      fi
-      rmdir "$RTCACHE_LOCKDIR"
-      )&
+      refresh_rt_cache 2>/dev/null &
     else
       echo "rtcache: lockdir ($RTCACHE_LOCKDIR) present. not refreshing."
     fi
@@ -69,7 +75,7 @@ function rt () {
     case $1 in
       res*,del*,take,steal,give)
         echo "updating rt-cache in background..."
-        rt-cache -r >/dev/null &
+        rt-cache -r 2>/dev/null &
         ;;
     esac
   fi
